version: "3.3"
services:
  oracle:
    image: "switchboardlabs/node:dev-v2-3-7-22"
    network_mode: host
    restart: always
    secrets:
      - PAYER_SECRETS
    environment:
      - LIVE=1
      - CLUSTER=${CLUSTER}
      - HEARTBEAT_INTERVAL=15 # Seconds
      - ORACLE_KEY=${ORACLE_KEY}
      - RPC_URL=${RPC_URL}
secrets:
  PAYER_SECRETS:
    file: ${PAYER_KEYPAIR}
